### ISSUE TITLE
Running Android Hello World Sample Results in Black Map Area and Crashes on Zoom

### ISSUE THREAD

**Issue by Zian** [Esri/runtime-questions#57]
Steps to Reproduce:
    1. Open the Hello World Android sample
    2. Run the application on any of the tested devices.
    3. Try to zoom in by using 2 fingers.

Tested Computers:
    - Lenovo ThinkPad T400 (Windows 7 x64)
    - Dell Vostro 3460 (Windows 8 x64)

Devices:
    - Samsung Galaxy Nexus (Android 4.4.4)
    - LG Nexus 4 (Android 5.1.1)
    - Asus Nexus 7 tablet (Android 5.1.1)

Stack trace:
07-19 09:52:10.691    3361-3361/android.arcgis.esri.com.helloworld E/InputEventReceiver﹕ Exception dispatching input event.
07-19 09:52:10.721    3361-3361/android.arcgis.esri.com.helloworld E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: android.arcgis.esri.com.helloworld, PID: 3361
    java.lang.RuntimeException: Error code: 3
    Error message: Invalid argument
    Additional error message: Scale can't be NAN
            at com.esri.arcgisruntime.internal.jni.CoreMapView.nativeInteractionZoomToScale(Native Method)
            at com.esri.arcgisruntime.internal.jni.CoreMapView.interactionZoomToScale(CoreMapView.java:220)
            at com.esri.arcgisruntime.internal.mapping.view.MapViewImpl.interactionZoomToScale(MapViewImpl.java:194)
            at com.esri.arcgisruntime.mapping.view.MapView.zoomToScale(MapView.java:631)
            at com.esri.arcgisruntime.mapping.view.DefaultMapViewOnTouchListener.onScale(DefaultMapViewOnTouchListener.java:604)
            at android.view.ScaleGestureDetector.onTouchEvent(ScaleGestureDetector.java:437)
            at com.esri.arcgisruntime.mapping.view.DefaultMapViewOnTouchListener.handleMultiTouch(DefaultMapViewOnTouchListener.java:398)
            at com.esri.arcgisruntime.mapping.view.DefaultMapViewOnTouchListener.onTouch(DefaultMapViewOnTouchListener.java:220)
            at com.esri.arcgisruntime.mapping.view.MapView.onTouchEvent(MapView.java:580)
            at android.view.View.dispatchTouchEvent(View.java:8471)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2399)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330)
            at android.view.View.dispatchPointerEvent(View.java:8666)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5752)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5897)
            at android.view.InputEventReceiver.di

**Comment by doneill** [comment]
This was resolved by updating the users development environment on the Lenovo, and in some instances when the device had no internet connection.
